version: '3.8'
name: twg_agency_backend
services:
  twg-backend:
    image: twg-backend
    build:
      context: ../twg-backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1m
    env_file:
      - ./environment.env
    volumes:
      #      - type: bind
      #        source: ../twg-backend/resources/images #/home/twg/resources/images
      #        target: /home/twg/images
      - ../twg-backend/resources/images:/home/twg/images
      - ../twg-backend/log:/log
    ports:
      - '8080:8080'
    networks:
      - backend
      - database
    restart: always

networks:
  backend:
    name: backend_network
  database:
    name: database_network
    external: true