version: '3.8'
name: twg_agency_backend
services:
  backend:
    image: twg-backend
    build:
      context: ../twg-backend
    env_file:
      - ./environment.env
    volumes:
      - type: bind
        source: ../twg-backend/resources/images #/home/twg/resources/images
        target: /home/twg/images
    ports:
      - "1337:1337"
    networks:
      - backend
      - database
    restart: always

networks:
  backend:
    name: backend_network
  database:
    name: database_network
    external: true