version: '3.8'
name: twg_agency_databases
services:
  postgres:
    image: postgres:alpine
    env_file:
      - ../environment.env
    volumes:
      - type: bind
        source: ../postgresql/data #/home/twg/postgresql/data
        target: /var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - database

  redis:
    image: redis:latest
    command: "redis-server /usr/local/etc/redis/redis.conf"
    env_file:
      - ../environment.env
    volumes:
      - type: bind
        source: ../redis #/home/twg/redis
        target: /var/lib/redis
      - type: bind
        source: ../redis.conf #/home/twg/redis.conf
        target: /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - database

networks:
  database:
    driver: bridge
    name: database_network