version: '3.8'
name: twg_agency_databases
services:
  postgres:
    image: postgres:alpine
    env_file:
      - ./environment.env
    volumes:
      - ../postgresql/backups:/home/backups
      - ../postgresql/data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - database

  redis:
    image: redis:latest
    command: "redis-server /usr/local/etc/redis/redis.conf"
    env_file:
      - ./environment.env
    volumes:
      - ../redis.conf:/usr/local/etc/redis/redis.conf
      - ../redis:/var/lib/redis
    ports:
      - "6379:6379"
    networks:
      - database

networks:
  database:
    driver: bridge
    name: database_network