version: '3.8'
name: twg_agency_frontend
services:
  twg-frontend:
    image: twg-frontend
    build:
      context: ../twg-frontend
    env_file:
      - ./environment.env
    volumes:
      - ../resources/images:/home/twg/images
    ports:
      - "80:3000"
      - "443:3000"
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: frontend_network
  backend:
    name: backend_network
    external: true