version: '3.8'
name: twg_agency_monitoring
services:
#  elk:
#    container_name: TWG_agency_elastic
#    image: sebp/elk
#    ports:
#      - "5601:5601" #kibana
#      - "9200:9200" #elastic
#      - "5044:5044" #logstash
#    networks:
#      - backend
#      - monitoring

  grafana:
    build: './config/grafana'
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    env_file:
      - ../environment.env
    networks:
      - backend
      - monitoring


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend
      - monitoring

networks:
  backend:
    name: backend_network
    external: true
  monitoring:
    name: monitoring_network