version: '3.8'
services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    env_file:
      - ./environment.env
  
    networks:
      - frontend
      - backend

networks:
  backend:
    name: backend_network
  frontend:
    name: frontend_network

volumes:
  ssl_data: