version: '3.8'
services:
  twg-proxy:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    env_file:
      - ./environment.env
  
    networks:
      - proxy
      - frontend
      - backend
      # - monitoring


networks:
  proxy:
    name: proxy_network
  frontend:
    name: frontend_network
    external: true
  backend:
    name: backend_network
    external: true
  # monitoring:
  #   name: monitoring_network
  #   external: true

volumes:
  ssl_data: